# capture_environment.R
# ---------------------------------------------------------------------------
# Record the computational environment for the Zenodo deposit.
#
# Writes two files:
#   renv.lock                        (repo root) exact version and source of
#                                    every package the analysis declares, in
#                                    the standard renv lockfile format, so the
#                                    environment can be restored with
#                                    renv::restore()
#   Analysis/output/session_info.txt human-readable R version, platform, BLAS,
#                                    locale and package versions
#
# WHY: the Methods stated package versions by hand ("R 4.4+, glmmTMB v1.1.14,
# ...") with nothing machine-readable behind them. A deposit meant to be re-run
# needs the real thing. See LICENSE-DATA.md and make_zenodo_archive.sh.
#
# DELIBERATELY NOT renv::init(). Initialising renv would write a project
# .Rprofile that auto-activates a project-local library, changing how every R
# session and every Quarto render in this repo behaves. We only want the
# lockfile as a record, so we snapshot the packages as currently installed and
# leave the project's R startup untouched.
#
# USAGE: Rscript Analysis/scripts/capture_environment.R
#
# Re-run this whenever a package used by the analysis is upgraded, and always
# immediately before building the deposit.
#
# EXPECTED, NOT A PROBLEM: renv reports that BiocManager and BiocVersion are
# "not installed [required by phangorn]". They are Bioconductor helpers that
# phangorn declares but that nothing here calls, and cmdstanr is an optional
# Stan backend we do not use. The lockfile is complete for this analysis. Any
# OTHER package appearing in those notices does mean the lockfile is short.

# ---- paths (same convention as the other scripts) -------------------------
.find_analysis_dir <- function() {
  d <- normalizePath(getwd(), winslash = "/")
  repeat {
    if (dir.exists(file.path(d, "data", "derived")) && dir.exists(file.path(d, "scripts"))) return(d)
    if (dir.exists(file.path(d, "Analysis", "data", "derived")))
      return(normalizePath(file.path(d, "Analysis"), winslash = "/"))
    parent <- dirname(d); if (identical(parent, d)) break; d <- parent
  }
  stop("Could not locate Analysis/. Run from inside the atlantic_birds repo.")
}
ANALYSIS_DIR <- .find_analysis_dir()
REPO         <- normalizePath(file.path(ANALYSIS_DIR, ".."), winslash = "/")
out_path     <- function(...) file.path(ANALYSIS_DIR, "output", ...)

note <- function(...) cat(..., "\n", sep = "")

# ---- 1. which packages does the analysis actually declare? ----------------
# Scan the live scripts and the manuscript sources only. archive/ is excluded
# on purpose: retired analyses must not pull dependencies into the lockfile.
if (!requireNamespace("renv", quietly = TRUE))
  stop("renv is required: install.packages('renv')")

scan_files <- c(
  list.files(file.path(ANALYSIS_DIR, "scripts"), pattern = "[.][Rr]$", full.names = TRUE),
  list.files(file.path(REPO, "Manuscript"),      pattern = "[.]qmd$",  full.names = TRUE)
)
note("Scanning ", length(scan_files), " files for declared dependencies ...")

deps <- renv::dependencies(scan_files, root = REPO, progress = FALSE, errors = "ignored")
pkgs <- sort(unique(deps$Package))

# Base and recommended packages ship with R and are not lockable.
base_pkgs <- rownames(installed.packages(priority = "base"))
pkgs      <- setdiff(pkgs, base_pkgs)

installed <- rownames(installed.packages())
missing   <- setdiff(pkgs, installed)
present   <- intersect(pkgs, installed)

note("  declared (non-base): ", length(pkgs))
if (length(missing)) {
  note("  NOT INSTALLED, so absent from the lockfile: ", paste(missing, collapse = ", "))
  note("  (optional backends such as cmdstanr are expected here; anything else ",
       "means the lockfile is incomplete)")
}

# ---- 2. renv.lock ---------------------------------------------------------
lockfile <- file.path(REPO, "renv.lock")
note("\nWriting ", lockfile, " ...")
renv::snapshot(
  project  = REPO,
  packages = present,
  lockfile = lockfile,
  prompt   = FALSE,
  force    = TRUE
)

# ---- 3. session_info.txt --------------------------------------------------
si_path <- out_path("session_info.txt")
note("Writing ", si_path, " ...")

con <- file(si_path, open = "wt")
on.exit(close(con), add = TRUE)
w <- function(...) writeLines(paste0(...), con)

w("Computational environment for:")
w("  Morphological stability and subtle phenotypic shifts in Atlantic Forest")
w("  birds across two decades of climate warming")
w("")
w("Generated by Analysis/scripts/capture_environment.R")
w("Captured:  ", format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"))
gitsha <- tryCatch(
  system2("git", c("-C", shQuote(REPO), "rev-parse", "HEAD"), stdout = TRUE, stderr = FALSE),
  error = function(e) NA_character_)
w("Git commit: ", if (length(gitsha) && !is.na(gitsha[1])) gitsha[1] else "(not a git checkout)")
w("")
w("Exact package versions and sources are in renv.lock at the repository root;")
w("restore that environment with renv::restore().")
w("")
w(strrep("=", 78))
w("")

si <- sessionInfo()
writeLines(capture.output(print(si)), con)

w("")
w(strrep("=", 78))
w("")
w("Packages declared by the analysis scripts and manuscript sources")
w("(scanned: Analysis/scripts/*.R, Manuscript/*.qmd; archive/ excluded)")
w("")
vers <- vapply(present, function(p)
  tryCatch(as.character(packageVersion(p)), error = function(e) "?"), character(1))
for (i in seq_along(present))
  w(sprintf("  %-16s %s", present[i], vers[i]))
if (length(missing)) {
  w("")
  w("Declared but not installed in the capturing environment:")
  for (m in missing) w(sprintf("  %-16s (absent)", m))
}

note("\nDone.")
note("  renv.lock          ", lockfile)
note("  session_info.txt   ", si_path)
